"""
Django settings for bookstore project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-13t-wl4ks==nc72@u0=+su!nr3076462#=bw^lld_9z4x4uy#g"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "AdminApp",
    "UserApp",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bookstore.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # add cart count context processor from UserApp
                "UserApp.views.cart_item_count",
                "UserApp.context_processors.translations",
            ],
        },
    },
]

WSGI_APPLICATION = "bookstore.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

# Supported languages
from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
    ('fr', _('French')),
]

# Optional: directory for locale files
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = os.path.join(BASE_DIR,"media")
MEDIA_URL = "/media/"
STATIC_URL = "/static/"
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'), ) 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Load Stripe keys from environment where possible. Keep existing test keys as fallback
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', "pk_test_51SPSuF0yVcFGnn0lMirtCTkWdikMyoLZRNnzMsGipkG7bg2lQJBJca3Fy5Y0q2XVZ8J29F0lPxIvLnDfeUpVPJDP009xjKHFXP")  # المفتاح العلني
# REMOVE any hardcoded Stripe secret if present here
# OLD example (remove if exists):
# STRIPE_SECRET_KEY = "sk_test_..." 

# NEW: load from environment to avoid committing secrets
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "STRIPE_SECRET_KEY")

# optional: fail fast in production
# if not STRIPE_SECRET_KEY and not DEBUG:
#     raise RuntimeError("STRIPE_SECRET_KEY is not set in environment")

# Webhook signing secret (recommended to set in environment)
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'STRIPE_SECRET_KEY')

# Security defaults (use env vars to control in production)
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))  # enable >0 in production
SECURE_BROWSER_XSS_FILTER = os.getenv('SECURE_BROWSER_XSS_FILTER', 'True') == 'True'
SECURE_CONTENT_TYPE_NOSNIFF = os.getenv('SECURE_CONTENT_TYPE_NOSNIFF', 'True') == 'True'
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

# In production set DEBUG=False and configure ALLOWED_HOSTS
DEBUG = os.getenv('DJANGO_DEBUG', str(DEBUG)) == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', ','.join(ALLOWED_HOSTS)).split(',') if os.getenv('ALLOWED_HOSTS') else ALLOWED_HOSTS

# Git helper: common command sequences to create/push repository
# A) Create a new local repo and push as main:
#   echo "# Book-Store" >> README.md
#   git init
#   git add .
#   git commit -m "first commit"
#   git branch -M main
#   git remote add origin https://github.com/hasan965/Book-Store.git
#   git push -u origin main
#
# B) Push an existing local repo/branch as main (no branch rename needed):
#   git remote add origin https://github.com/hasan965/Book-Store.git
#   git push -u origin HEAD:main
#
# C) Push a specific local branch (e.g., feature-branch):
#   git checkout -b feature-branch   # create if needed
#   git add .
#   git commit -m "your message"
#   git push -u origin feature-branch
#
# D) Remote 'origin' already exists — options:
#   1) Update the URL (keeps existing remote name and config):
#      git remote set-url origin https://github.com/hasan965/Book-Store.git
#
#   2) Remove and re-add origin:
#      git remote remove origin
#      git remote add origin https://github.com/hasan965/Book-Store.git
#
# After fixing remote, push a branch (example: feature-branch):
#   git checkout -b feature-branch   # create if needed
#   git add .
#   git commit -m "your message"
#   git push -u origin feature-branch
#
# Or push current HEAD as a remote branch without creating a local branch:
#   git push origin HEAD:feature-branch
#
# Troubleshooting:
# - If "src refspec ... does not match any" → ensure branch has at least one commit.
# - Check current branch: git status
# - List branches: git branch
# - For HTTPS auth, use a Personal Access Token if prompted.

