# Generated by Django 4.1.2 on 2022-11-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="pname",
            field=models.CharField(max_length=70),
        ),
    ]
