# Generated by Django 4.1.2 on 2022-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0002_alter_product_description_alter_product_pname"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("emai", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "UserInfo",
            },
        ),
    ]
