# Generated by Django 4.1.2 on 2022-12-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0005_product_p_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
